require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IndicesController do

  # This should return the minimal set of attributes required to create a valid
  # Index. As you add validations to Index, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IndicesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all indices as @indices" do
      index = Index.create! valid_attributes
      get :index, {}, valid_session
      assigns(:indices).should eq([index])
    end
  end

  describe "GET show" do
    it "assigns the requested index as @index" do
      index = Index.create! valid_attributes
      get :show, {:id => index.to_param}, valid_session
      assigns(:index).should eq(index)
    end
  end

  describe "GET new" do
    it "assigns a new index as @index" do
      get :new, {}, valid_session
      assigns(:index).should be_a_new(Index)
    end
  end

  describe "GET edit" do
    it "assigns the requested index as @index" do
      index = Index.create! valid_attributes
      get :edit, {:id => index.to_param}, valid_session
      assigns(:index).should eq(index)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Index" do
        expect {
          post :create, {:index => valid_attributes}, valid_session
        }.to change(Index, :count).by(1)
      end

      it "assigns a newly created index as @index" do
        post :create, {:index => valid_attributes}, valid_session
        assigns(:index).should be_a(Index)
        assigns(:index).should be_persisted
      end

      it "redirects to the created index" do
        post :create, {:index => valid_attributes}, valid_session
        response.should redirect_to(Index.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved index as @index" do
        # Trigger the behavior that occurs when invalid params are submitted
        Index.any_instance.stub(:save).and_return(false)
        post :create, {:index => {  }}, valid_session
        assigns(:index).should be_a_new(Index)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Index.any_instance.stub(:save).and_return(false)
        post :create, {:index => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested index" do
        index = Index.create! valid_attributes
        # Assuming there are no other indices in the database, this
        # specifies that the Index created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Index.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => index.to_param, :index => { "these" => "params" }}, valid_session
      end

      it "assigns the requested index as @index" do
        index = Index.create! valid_attributes
        put :update, {:id => index.to_param, :index => valid_attributes}, valid_session
        assigns(:index).should eq(index)
      end

      it "redirects to the index" do
        index = Index.create! valid_attributes
        put :update, {:id => index.to_param, :index => valid_attributes}, valid_session
        response.should redirect_to(index)
      end
    end

    describe "with invalid params" do
      it "assigns the index as @index" do
        index = Index.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Index.any_instance.stub(:save).and_return(false)
        put :update, {:id => index.to_param, :index => {  }}, valid_session
        assigns(:index).should eq(index)
      end

      it "re-renders the 'edit' template" do
        index = Index.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Index.any_instance.stub(:save).and_return(false)
        put :update, {:id => index.to_param, :index => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested index" do
      index = Index.create! valid_attributes
      expect {
        delete :destroy, {:id => index.to_param}, valid_session
      }.to change(Index, :count).by(-1)
    end

    it "redirects to the indices list" do
      index = Index.create! valid_attributes
      delete :destroy, {:id => index.to_param}, valid_session
      response.should redirect_to(indices_url)
    end
  end

end
